version: '3.8'

services:
  cisco-backup-web:
    build: .
    container_name: cisco_backup_manager
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app
      - ./network_backups:/app/backups
    restart: unless-stopped

volumes:
  db_data: